# Generated by Django 4.0 on 2022-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('Fundacja', 'Fundacja'), ('Organizacja pozarządowa', 'Organizacja pozarządowa'), ('Zbiórka lokalna', 'Zbiórka lokalna')], max_length=32),
        ),
    ]
